name: network_arch
description:
  NetworkArch is a network diagnostic tool equipped with various utilities,
  including pinging specific IP address or hostname, sending Wake on LAN magic packets,
  whois and DNS Lookup.
publish_to: "none"
version: 1.3.1+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  auto_animated: ^3.0.1
  bloc: ^8.0.3
  carrier_info: ^2.0.5
  cupertino_icons: ^1.0.5
  cupertino_lists: ^1.0.1
  dart_ping: ^6.1.2
  dart_ping_ios: ^1.1.0
  dynamic_color: ^1.4.0
  elegant_notification: ^1.5.4
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  feedback: ^2.5.0
  feedback_sentry: ^2.3.0
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  # dbus version solving issue
  flutter_platform_widgets: ^1.20.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.7
  google_mobile_ads: ^1.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  hydrated_bloc: ^8.1.0
  in_app_purchase: ^3.0.4
  introduction_screen: ^3.0.2
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lan_scanner: ^3.4.1
  modal_bottom_sheet: ^2.0.1
  network_info_plus: ^2.1.3
  package_info_plus: ^1.4.2
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  sentry_flutter: ^6.5.1
  url_launcher: ^6.1.2
  wake_on_lan: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.8.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/dark_mode_map_style.txt
    - assets/icons/icon_alpha_light.svg
    - assets/icons/icon_alpha_dark.svg
